apiVersion: apps/v1
kind: Deployment
metadata:
  name: fantasy-football
  labels:
    app: fantasy-football
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fantasy-football
  template:
    metadata:
      labels:
        app: fantasy-football
    spec:
      containers:
        - name: fantasy-football
          image: fantasy-football:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fantasy-football-secret
                  key: SECRET_KEY
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGODB_URI
              value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb:27017/fantasy_football?authSource=admin"
            - name: MONGO_TIMEOUT_MS
              value: "5000"
